Hartelijk dank voor uw bijdrage aan onze gelokaliseerde inhoud.

Alle bijdragen aan onze inhoud moeten voldoen aan de volgende richtlijnen:

1. [Microsoft Language Style Guide](https://www.microsoft.com/Language/StyleGuides) waarin wordt beschreven hoe de vertaling van het Engels naar een andere taal moet lezen.

2. [Microsoft Language Portal](https://www.microsoft.com/language) bevat Engelse **termen** met betrekking tot technologie en de bijbehorende vertalingen die in de Microsoft-producten worden gebruikt.

Als u zich aansluit bij onze steeds groter wordende lokalisatiecommunity, kunt u [Community Localization Wiki](https://github.com/Microsoft/Localization/wiki) bezoeken voor meer informatie over het programma voor lokalisatie door de community en andere manieren waarop u kunt bijdragen aan het programma. Ook delen we op deze pagina het goedkeuringsproces voor pull-aanvragen en een aantal tips voor <PR management>.
Voor uw bijdragen aan <localization> ontvangt u punten. Blijf uw bijdragen dus insturen om uw positie op [Contributors' Leaderboard](https://microsoftl10n.github.io/) te verbeteren.

Internationale groep voor Microsoft-ontwikkelaarsrelaties
